// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPOkOssVSv8Likw8laXoqC3EX-dtZ911Q',
    appId: '1:71805003268:android:516aa06aceb3a127bdb751',
    messagingSenderId: '71805003268',
    projectId: 'mobiletravelapp-7d8b1',
    storageBucket: 'mobiletravelapp-7d8b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8aYNeQAWwk5MBPyI3CCyXSuYJyLbaFYs',
    appId: '1:71805003268:ios:8eb77d118d2a07d3bdb751',
    messagingSenderId: '71805003268',
    projectId: 'mobiletravelapp-7d8b1',
    storageBucket: 'mobiletravelapp-7d8b1.appspot.com',
    iosClientId: '71805003268-1809liu517vdulg6jqedbkmkgeotbdi9.apps.googleusercontent.com',
    iosBundleId: 'com.edwinzuluaga.mobiletravelapp',
  );
}
